services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: medvault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - medvault-postgres:/var/lib/postgresql/data
  redis:
    image: redis:8-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - medvault-redis:/data

volumes:
  medvault-postgres:
  medvault-redis:
